### PR TITLE
Migration to Jakarta EE 10

### LINKED ISSUE #56: JAXB Upgrade Plan
Hello,

Is there a plan or roadmap to upgrading the JAXB version to Jakarta XML Binding 3.0/4.0+? We have another dependency on it via an internal project, which as a result also needs to be kept at the same JAXB version, so we were looking into upgrading it across the board if possible.

Thanks!

### PR DESCRIPTION
**Pull request by essobedo**
fixes #56

## Motivation

Many frameworks like Spring Boot, Quarkus, Camel... have made the Jakarta EE 10 migration which makes the lib incompatible with them. The goal of these changes is to migrate the lib to make it compatible again with the frameworks.

## Modifications:

* Change the default Java version to 11
* Replace the Javax dependencies with the corresponding Jakarta dependencies
* Replace the `javax` imports with the corresponding `jakarta` imports
* Remove the note regarding the dependency `javax.xml.bind` to add as it is no more needed
* Force the Java version in all projects
* Remove the specific launcher for Java 11
* Fix the tests in `MxWriteWithAdaptersTest` using incorrect zone offsets
* Disable the test `Issue11` with a description of the problem to fix

### CODE REVIEW

**Comment by essobedo** [comment]
Depends on https://github.com/prowide/prowide-core/pull/151, the current PR contains temporary changes to be removed once `prowide-core` will be released

**Comment by zubri** [comment]
Hi @essobedo thanks for the initiative! This is something we have to do, for sure. 

We normally do major releases by May, along the SRU updates (messages schemas for upcoming SWIFT standard releases). So that would be a good opportunity to launch this migration. So we will take your PR as a starting point. 

As you might have noticed 99% of this project is generated code, so we have to update the codegen too. I'm not sure yet what are the implications to move from the legacy xjc to the new Jakarta xjc tool, but I guess it is pretty much the same.

Within this major update I'd like to add also an adapter to generate LocalDate in the model instead of XMLGregorianCalendar.

(The codegen is not public since it contains an XSDs distribution that cannot be publicly disclose)

**Comment by essobedo** [comment]
@zubri thx for your answer, I understand that your major releases are in May but I was wondering if it could be possible to have at least an alpha or milestone version sooner more or less based on those PRs to be able to test it already on Camel / Camel Quarkus. WDYT? Is it doable? In Camel and Camel Quarkus, we had to remove the corresponding component as it is not compatible, ideally, I would like to be able to re-add it even if it is an alpha/experimental version.

**Comment by zubri** [comment]
We could use SNAPSHOT versions for early testing. They would be hosted in OSS Sonatype, but not in maven Central though.

**Comment by zubri** [comment]
OK you mean for camel-swift I guess. 
I think it's ok. We had only pushed final releases to Maven Central so far, but for this particular migration an alpha would make sense. Let me find some time to update the codegen and we'll do an alpha release.

**Comment by essobedo** [comment]
> OK you mean for camel-swift I guess. 

Exactly

> I think it's ok. We had only pushed final releases to Maven Central so far, but for this particular migration an alpha would make sense. Let me find some time to update the codegen and we'll do an alpha release.

Great news! many thanks 🙏

**Comment by sman-81** [comment]
> Task linked: [CU-2np2uh3 GH-56 ⁃ JAXB Upgrade Plan](https://app.clickup.com/t/2np2uh3)

This link leads into a 404. Could you check please?

**Comment by zubri** [comment]
> > Task linked: [CU-2np2uh3 GH-56 ⁃ JAXB Upgrade Plan](https://app.clickup.com/t/2np2uh3)
> 
> This link leads into a 404. Could you check please?

No problem. That was generated automatically by ClickUp. We use ClickUp internally in Prowide to follow up tasks assignment to internal developers. However, relevant technical information for the PR is here at GitHub with public visibility.

**Pull request merged**
